apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 1080
    - protocol: TCP
      port: 8025
      targetPort: 1025